FROM alpine:3.22

RUN apk add --no-cache \
    catch2-3 \
    cmake \
    curl-dev \
    fmt-dev \
    g++ \
    gcompat \
    gdb \
    git \
    nlohmann-json \
    openssl-dev \
    procps \
    samurai \
    sqlite-dev \
    strace \
    tzdata
